# Generated by Django 4.1.1 on 2022-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_LEARNING", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
