# Generated by Django 4.1.1 on 2022-09-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("published", models.DateField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False)),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
            ],
        ),
        migrations.CreateModel(
            name="BookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_10", models.CharField(blank=True, max_length=20)),
                ("isbn_13", models.CharField(blank=True, max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="Crud.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="numbers",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Crud.booknumber",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                (
                    "books",
                    models.ManyToManyField(related_name="authors", to="Crud.book"),
                ),
            ],
        ),
    ]
